# Python 기초

Python에서는 변수를 선언할 때, 따로 변수 형태를 선언할 필요가 없다.

Python의 기본 자료형은 다음과 같다.
* Number : int(0 포함 정수), float(실수)
* String : 텍스트 문자열 "Hello World"
* List : ListName = [element1, element2, ...]
* Tuple : TupleNmae = (element1, element2, ...)
* Dictionary : key와 value의 쌍으로 구성됨. DicName = {key1:value1, key2:value2, ...}
* Set : SetName = set([1, 2, 3, ...])
* Bool : True/False


List와 tuple은 모두 비슷한 데이터를 하나의 집합으로 구성한 자료형이라는 점은 같으나, list는 배열의 크기나 원소의 값을 바꿀 수 있고(mutable), tuple은 한 번 정해진 배열은 바꿀 수 없다(immutable)는 점에서 차이가 있다. 데이터의 변형이 빈번히 필요한 머신러닝에서는 주로 list가 많이 쓰인다. Dictionary는 대응관계를 나타내는 자료형으로, list나 tuple과는 다르게 index가 아닌 key값으로 요소값에 접근한다.

# 1. 자료형 살펴보기

이 장에서는 Python의 자료형에 대해 설명한다.

차례로 코딩을 따라하면서 문법을 숙지하고, 코드에 대한 주석을 반드시 읽어보도록 한다.

# 1-1. 숫자

**숫자형 변수의 종류**

In [ ]:
# 숫자형 변수의 종류
num1 = 3 # 정수
num2 = 3.45 # 실수
num3 = 3.14e10 # 실수
num4 = 0b1010 # 2진수. 숫자 앞 접두어 0b
num5 = 0o14 # 8진수. 숫자 앞 접두어 0o
num6 = 0x12 # 16진수. 숫자 앞 접두어 0x

# 숫자형 변수 값과 타입을 print함수로 display하여 확인
# 머신러닝에서는 사용하고자 하는 데이터의 변수 타입을 확인하는 것이 매우 중요하다.
# 데이터의 타입은 type() 함수로 확인 가능하다.
print("아래는 숫자형 변수의 값과 타입이다.")  
print("\n") # 줄바꿈
print(num1,'의 자료형은', type(num1))
print(num2,'의 자료형은', type(num2))
print(num3,'의 자료형은', type(num3))
print(num4,'의 자료형은', type(num4))
print(num5,'의 자료형은', type(num5))
print(num6,'의 자료형은', type(num6))


아래는 숫자형 변수의 값과 타입이다.


3 의 자료형은 <class 'int'>
3.45 의 자료형은 <class 'float'>
31400000000.0 의 자료형은 <class 'float'>
10 의 자료형은 <class 'int'>
12 의 자료형은 <class 'int'>
18 의 자료형은 <class 'int'>


**숫자형 변수 연산**

In [ ]:
# 숫자형 변수 연산 - 연산에 따른 자료형 변화에 주의
sum1 = num1 + num1 # int + int => int
sum2 = num1 + num2 # int + float => float
sub1 = num1 - num1 # int - int => int
sub2 = num2 - num1 # float - int => float
mul1 = num1 * num1 # int * int => int
mul2 = num1 * num2 # int * float => float
div1 = num1/num1 # int / int => float
div2 = num1/num2 # int / float => float
div3 = num2//num1 # 몫 구하기 연산
div4 = num2%num1 # 나머지 구하기 연산

print("숫자형 변수의 연산에 따른 자료형 변화\n") # 줄바꿈 \n는 뒤에 붙여 쓸 수 있다.
print('3 + 3 = ', sum1, type(sum1))
print('3 + 3.45 = ', sum2, type(sum2))
print('3 - 3 = ', sub1, type(sub1))
print('3.45 - 3 = ', sub2, type(sub2))
print('3 * 3 = ', mul1, type(mul1))
print('3 * 3.45 = ', mul2, type(mul2))
print('3 / 3 = ', div1, type(div1))
print('3 / 3.45 = ', div2, type(div2))
print('3.45 나누기 3의 몫은 ', div3, type(div3))
print('3.45 나누기 3의 나머지는 ', div4, type(div4))

숫자형 변수의 연산에 따른 자료형 변화

3 + 3 =  6 <class 'int'>
3 + 3.45 =  6.45 <class 'float'>
3 - 3 =  0 <class 'int'>
3.45 - 3 =  0.4500000000000002 <class 'float'>
3 * 3 =  9 <class 'int'>
3 * 3.45 =  10.350000000000001 <class 'float'>
3 / 3 =  1.0 <class 'float'>
3 / 3.45 =  0.8695652173913043 <class 'float'>
3.45 나누기 3의 몫은  1.0 <class 'float'>
3.45 나누기 3의 나머지는  0.4500000000000002 <class 'float'>


# 1-2. 문자열

**문자열 변수 생성 방법**

In [ ]:
# <문자열 변수>
# 문자열 변수를 만드는 방법은 총 4가지가 있다.
str1 = 'Hello'
str2 = "World"
str3 = """Hello World"""
str4 = '''Hello World'''

print('str1 : ', str1)
print('str2 : ', str2)
print('str3 : ', str3)
print('str4 : ', str4)
print(type(str1))

str1 :  Hello
str2 :  World
str3 :  Hello World
str4 :  Hello World
<class 'str'>


In [ ]:
# 문자열 변수를 만드는 방법이 다양한 이유는 문자열 안에 따옴표를 포함시키기 위함이다. 
str5 = 'She said, "Nice to meet you."' # 문자열 안에 큰따옴표 포함시키기
str6 = "He said, \"Nice to meet you too.\"" # 백슬래시를 사용하여 큰따옴표 포함시키기
str7 = "Python's syntax" # 문자열 안에 작은따옴표 포함시키기
str8 = 'Python\'s syntax' # 백슬래시를 사용하여 작은따옴표 포함시키기

print('str5 : ', str5)
print('str6 : ', str6)
print('str7 : ', str7)
print('str8 : ', str8)

str5 :  She said, "Nice to meet you."
str6 :  He said, "Nice to meet you too."
str7 :  Python's syntax
str8 :  Python's syntax


**문자열 변수 연산**

In [ ]:
# 문자열 연산
strsum1 = str1 + str2
strsum2 = str1 + ' ' + str2 # 두 문자열 변수 사이에 띄어쓰기 넣기
strsum3 = '"' + str1 + ' ' + str2 + '"' # 큰따옴표 추가하기
strsum4 = "Peter\'s friend said, " + '"' + str1 + '"' # 문자열 덧셈 연산 응용하기
strmul1 = str1 * 2 # 문자열 곱하기 연산

print('strsum1 : ', strsum1)
print('strsum2 : ', strsum2)
print('strsum3 : ', strsum3)
print('strsum4 : ', strsum4)
print('strmul1 : ', strmul1)

strsum1 :  HelloWorld
strsum2 :  Hello World
strsum3 :  "Hello World"
strsum4 :  Peter's friend said, "Hello"
strmul1 :  HelloHello


**문자열 인덱싱**

In [ ]:
# 문자열 인덱싱
print("str1의 첫 번째, 두 번째 elements : ", str1[0], str1[1])
print("str1의 뒤에서 첫 번째 element : ", str1[-1]) 
print("str1의 뒤에서 네 번째 element : ", str1[-4]) 

# 문자열의 요소들을 따로 접근하여 출력한 경우,
# 문자열의 요소들 사이에 띄어쓰기가 되어 있음을 알 수 있다.
print("문자열의 요소들을 따로 접근하여 출력 : ", str1[0], str1[1], str1[2], str1[3], str1[4]) 

# 문자열의 요소들을 띄어쓰기 없이 붙여서 출력하고 싶다면 sep을 파라미터로 넣어 주면 된다.
print("띄어쓰기를 제거하여 출력 : ", str1[0], str1[1], str1[2], str1[3], str1[4], sep = '') 

str1의 첫 번째, 두 번째 elements :  H e
str1의 뒤에서 첫 번째 element :  o
str1의 뒤에서 네 번째 element :  e
문자열의 요소들을 따로 접근하여 출력 :  H e l l o
띄어쓰기를 제거하여 출력 : Hello


**문자열 슬라이싱**

In [ ]:
# 문자열 슬라이싱
# 대괄호 안에 시작지점의 인덱스와 끝지점의 인덱스를 넣어 슬라이싱(잘라내기)할 수 있다.
# => 변수[시작번호:끝번호]

print("str1[0:4] : ", str1[0:4])

# 원래대로라면 str1[4]는 5개의 알파벳으로 이루어진 'Hello'에서 마지막 요소인 'o'에 해당하지만
# 출력해 본 결과 'Hell'까지만 출력되는 것을 알 수 있다.
# 이렇듯 슬라이싱에서는 끝번호에 해당하는 요소는 잘라내지 않음에 주의해야 한다.


# 슬라이싱에서의 인덱스는 혼동하기 쉬우므로 아래 슬라이싱 예를 통해 숙지하도록 한다.
print('str1[0:5] : ', str1[0:5])
print('str1[0:-1] : ', str1[0:-1]) # 오른쪽에서 첫 번째 해당하는 요소인 o를 제외한 나머지 가져오기
print('str1[0:] : ', str1[0:])
print('str1[3:4] : ', str1[3:4])
print('str1[3:5] : ', str1[3:5])
print('str1[0:3] + str1[3:5] : ', str1[0:3] + str1[3:5])
print(str1[0:2] + ' ' + str1[2:-1])

str1[0:4] :  Hell
str1[0:5] :  Hello
str1[0:-1] :  Hell
str1[0:] :  Hello
str1[3:4] :  l
str1[3:5] :  lo
str1[0:3] + str1[3:5] :  Hello
He ll


**문자열 포맷**
  
%s : 문자열 (string)

%c : 문자 1개 (character)

%d : 정수 (integer)

%f : 부동소수 (floating-point)

%b : 2진수

%o : 8진수

%x : 16진수

%% : %


In [ ]:
# 문자열 포맷 이용하기
# 문자열 안에서는 %를 사용하여 원하는 변수의 값을 문자열에 포함시킬 수 있다.
str_f1 = "It's %d o'clock" % 3
print(str_f1)

# {} 기호를 이용하면 자료형에 상관없이 삽입이 가능하다.
str_f2 = "From {} AM To {} PM.".format(9, 6)
str_f3 = "From {} AM To {} PM.".format(9, 'Six')
print(str_f2)
print(str_f3)

It's 3 o'clock
From 9 AM To 6 PM.
From 9 AM To Six PM.


In [ ]:
# 소수점 표현하기
a = 3.141592
str_f4 = "a is {}".format(a)
print(str_f4)
str_f5 = "a is {:0.4f}".format(a) # 소수점 4자리까지 표현
print(str_f5)
str_f6 = "a is %0.3f" %a # 소수점 3자리까지 표현
print(str_f6)

a is 3.141592
a is 3.1416
a is 3.142


**문자열 관련 함수**

문자 개수 세기 : count

위치 찾기 : find 또는 index

문자열 합치기 :  join

소문자 -> 대문자 : upper

대문자 -> 소문자 : lower

왼쪽 공백 지우기 : lstrip

오른쪽 공백 지우기 : rstrip

양쪽 공백 지우기 : strip

문자열 바꾸기 : replace

문자열 나누기 : split

In [ ]:
# 문자 개수 세기
count_hello = str1.count('l') 
print('Hello에서 l의 개수 : ', count_hello)

# 위치 찾기
find_e = str1.find('e')
index_e = str1.index('e')
print("find 함수로 'Hello'에서 e의 위치 찾기 : ", find_e)
print("index 함수로 'Hello'에서 e의 위치 찾기 : ", index_e)
print('\n')

Hello에서 l의 개수 :  2
find 함수로 'Hello'에서 e의 위치 찾기 :  1
index 함수로 'Hello'에서 e의 위치 찾기 :  1




In [ ]:
# 문자열 합치기
hello_list = ['H', 'e', 'l', 'l', 'o'] # 5개의 캐릭터로 이루어진 리스트 변수 선언
print('hello_list : ', hello_list)
join_hello1 = ','.join(hello_list) # hello_list의 요소들 사이에 ',' 구분자를 넣어서 합치기
join_hello2 = ''.join(hello_list) # hello_list의 요소들 사이에 구분자 없이 합치기
print('element 사이에 콤마 넣어서 합치기 : ', join_hello1)
print('element 사이에 구분자 없이 합치기 : ', join_hello2)
print('\n')

hello_list :  ['H', 'e', 'l', 'l', 'o']
element 사이에 콤마 넣어서 합치기 :  H,e,l,l,o
element 사이에 구분자 없이 합치기 :  Hello




In [ ]:
# 대소문자 변환
upper_hello = str1.upper()
lower_hello = str1.lower()
print('Hello를 모두 대문자로 전환 : ', upper_hello)
print('Hello를 모두 소문자로 전환 : ', lower_hello)
print('\n')

Hello를 모두 대문자로 전환 :  HELLO
Hello를 모두 소문자로 전환 :  hello




In [ ]:
# 공백 지우기
a = " Hi "
print(a.lstrip())
print(a.rstrip())
print(a.strip())
print('\n')

# 문자열 바꾸기
b = "That is great"
c = b.replace('That', 'Python')
print(c)

# 문자열 나누기
print(b.split(' ')) # 띄어쓰기 기준으로 나누기
print(b.split('a')) # a 기준으로 나누기

Hi 
 Hi
Hi


Python is great
['That', 'is', 'great']
['Th', 't is gre', 't']


# 1-3. 리스트

**리스트 생성 및 요소 접근하기**

In [ ]:
# 리스트변수명 = [요소1, 요소2, ...]
emptyList = []
numList = [1, 2, 3]
strList = ['This', 'is', 'a list']
print('emptyList = ', emptyList)
print('numList = ', numList)
print('strList = ', strList)
print(type(numList), '\n') # 변수 타입 확인하기

# 리스트 요소 접근하기
print('numList의 3번째 요소 : ', numList[2], '\n')

# 리스트 안에는 어떠한 자료형도 포함 가능하다.
anylist = [1, 3.14, 'Python', ['Java', 'C']]
print(anylist[0], type(anylist[0]))
print(anylist[1], type(anylist[1]))
print(anylist[2], type(anylist[2]))
print(anylist[3], type(anylist[3]))
print(anylist[3][0], type(anylist[3][0])) 

emptyList =  []
numList =  [1, 2, 3]
strList =  ['This', 'is', 'a list']
<class 'list'> 

numList의 3번째 요소 :  3 

1 <class 'int'>
3.14 <class 'float'>
Python <class 'str'>
['Java', 'C'] <class 'list'>
Java <class 'str'>


**리스트 연산**

In [ ]:
# 더하기(+)와 반복하기(*)
sumList = numList + strList
print('sumList = ', sumList)
mulList = numList * 2 
print('mulList = ', mulList)
print('\n')

# 리스트 수정, 삭제
numList2 = [2, 4, 6]
print('numList2 = ', numList2)
numList2[1] = 5 # 두 번째 요소 수정
print('numList2 = ', numList2)
del numList2[1] # 두 번째 요소 삭제
print('numList2 = ', numList2)

sumList =  [1, 2, 3, 'This', 'is', 'a list']
mulList =  [1, 2, 3, 1, 2, 3]


numList2 =  [2, 4, 6]
numList2 =  [2, 5, 6]
numList2 =  [2, 6]


**리스트 관련 함수**

리스트 길이 : len

리스트에 포함된 요소 개수 세기 : count

리스트 확장 및 요소 추가 : append, extend, insert

정렬 : sort

뒤집기 : reverse

위치 찾기 : index

요소 제거 : remove, del

In [ ]:
# 리스트 길이
# 리스트 길이를 재는 함수 len()은 머신러닝에서 필수적인 함수이므로 꼭 숙지할 것
numList1 = [1, 2, 1, 4, 5]
numList2 = [3, 6, 9]
len(numList1)
print('numList1 = ', numList1, ' 의 길이는 ', len(numList1), '\n')

numList1 =  [1, 2, 1, 4, 5]  의 길이는  5 



In [ ]:
# 리스트의 요소 개수 
numList1.count(1)
print('numList1에서 1의 개수는 ', numList1.count(1), '\n')

# 리스트 확장 및 요소 추가
# append는 리스트 끝에 인자로 전달된 변수를 그대로 추가한다.
# extend는 인자로 전달된 iterable의 모든 요소를 리스트에 추가한다.
# insert는 인자로 전달된 index의 위치에 요소를 추가한다.
# append, extend, insert 모두 리스트를 확장하는 함수로,
# 혼동하기 쉬우니 아래 예시를 통해 숙지하도록 한다

numList1.append(7) 
print('numList1에 7이 추가됨 => ', numList1)
numList2.append([7, 8])
print('append 함수로 numList2의 끝에 배열 [7, 8]이 통째로 추가됨 => ', numList2)
numList2.extend([7, 8])
print('extend 함수로 numList2의 끝에 배열 [7, 8]의 요소들이 추가됨 => ', numList2)
numList1.insert(0, [7, 8])
print('insert 함수로 numList1의 첫 index에 배열 [7, 8]이 추가됨 => ', numList1)
print('\n')

numList1에서 1의 개수는  2 

numList1에 7이 추가됨 =>  [1, 2, 1, 4, 5, 7]
append 함수로 numList2의 끝에 배열 [7, 8]이 통째로 추가됨 =>  [3, 6, 9, [7, 8]]
extend 함수로 numList2의 끝에 배열 [7, 8]의 요소들이 추가됨 =>  [3, 6, 9, [7, 8], 7, 8]
insert 함수로 numList1의 첫 index에 배열 [7, 8]이 추가됨 =>  [[7, 8], 1, 2, 1, 4, 5, 7]




In [ ]:
# 리스트 정렬
# sort함수는 기본적으로 오름차순(reverse=False)이 default이다.
# 내림차순으로 정렬하고 싶다면 reverse=True를 인자로 주면 된다.
numList3 = [3, 10, 1, 100, 34]
numList3.sort()
print('numList3 오름차순 정렬 : ', numList3)
numList3.sort(reverse=True)
print('numList3 내림차순 정렬 : ', numList3)
print('\n')

# 리스트 순서 뒤집기
numList4 = [10, 7, 6, 4, 7, 2, 3]
numList4.reverse()
print('numList4 순서 뒤집기 => ', numList4, '\n')

numList3 오름차순 정렬 :  [1, 3, 10, 34, 100]
numList3 내림차순 정렬 :  [100, 34, 10, 3, 1]


numList4 순서 뒤집기 =>  [3, 2, 7, 4, 6, 7, 10] 



In [ ]:
# 리스트 요소 위치 찾기
numList4[1]
print('numList4의 두 번째 요소 : ', numList4[1])

# 리스트 요소 제거
# del은 함수가 아니라 예약어이므로 'del 리스트[인덱스]'의 형태로 사용한다.
# remove는 리스트에서 첫 번째로 등장하는 요소를 제거한다.

del numList4[0]
print(numList4) 

numList4.remove(7) # 남은 [2, 7, 4, 6, 7, 10]에서 첫 번째로 등장하는 7을 제거
print(numList4)

numList4.remove(7) # 이후 한 번 더 같은 코드를 반복하면 남은 7도 제거됨
print(numList4)

numList4의 두 번째 요소 :  2
[2, 7, 4, 6, 7, 10]
[2, 4, 6, 7, 10]
[2, 4, 6, 10]


# 1-4. 튜플

**튜플 생성 및 요소 접근하기**

In [ ]:
# 튜플변수명 = (요소1, 요소2, ...)
emptyTuple = ()
numTuple = (1, 2, 3)
strTuple = ('This', 'is', 'a tuple')
print('emptyTuple = ', emptyTuple)
print('numTuple = ', numTuple)
print('strTuple = ', strTuple)
print(type(emptyTuple), '\n') # 변수 타입 확인하기

# 튜플 요소 접근하기 - 리스트와 같이 [index]로 접근 가능
print('numTuple의 2번째 요소 : ', numTuple[1], '\n')

# 리스트와 마찬가지로 튜플에는 어떠한 자료형도 포함 가능하다.
anyTuple = (1, 3.14, 'Python', ['Java', 'C'], (34, 45, 56))
print(anyTuple[0], type(anyTuple[0]))
print(anyTuple[1], type(anyTuple[1]))
print(anyTuple[2], type(anyTuple[2]))
print(anyTuple[3], type(anyTuple[3]))
print(anyTuple[4], type(anyTuple[4]))
print(anyTuple[3][0], type(anyTuple[3][0]))
print(anyTuple[4][1], type(anyTuple[4][1]))

emptyTuple =  ()
numTuple =  (1, 2, 3)
strTuple =  ('This', 'is', 'a tuple')
<class 'tuple'> 

numTuple의 2번째 요소 :  2 

1 <class 'int'>
3.14 <class 'float'>
Python <class 'str'>
['Java', 'C'] <class 'list'>
(34, 45, 56) <class 'tuple'>
Java <class 'str'>
45 <class 'int'>


# 1-5. 딕셔너리

**딕셔너리 생성 및 요소 접근하기**



In [ ]:
# 딕셔너리변수명 = {key1:value1, key2:value2, ...}
student_dict = {'name':'Jinho', 'age':22, 'gender':'male'}
print(student_dict)

# key를 통해 value에 access
print(student_dict['name'])
print(student_dict['age'])
print(student_dict['gender'])

# 변수 타입 확인하기
print(type(student_dict))

# key는 unique한 값이어야 한다. 중복되면 마지막 정보만 남는다.
a = {1:'one', 1:'two'}
print(a)

{'name': 'Jinho', 'age': 22, 'gender': 'male'}
Jinho
22
male
<class 'dict'>
{1: 'two'}


**딕셔너리 관련 함수**

key 리스트 만들기 : keys

value 리스트 만들기 : values

key, value 쌍 얻기 : items

key, value 쌍 모두 지우기 : clear

key로 value 얻기 : get

해당 key가 딕셔너리 안에 있는지 조사 : in

In [ ]:
num_dict = {1:'one', 2:'two', 3:'three'}

# 모든 key값 추출
allkeys = num_dict.keys()
print(allkeys, type(allkeys))

# 모든 value값 추출
allvalues = num_dict.values()
print(allvalues, type(allvalues))

# key, value 쌍 얻기
kv_pairs = num_dict.items()
print(kv_pairs, type(kv_pairs))

dict_keys([1, 2, 3]) <class 'dict_keys'>
dict_values(['one', 'two', 'three']) <class 'dict_values'>
dict_items([(1, 'one'), (2, 'two'), (3, 'three')]) <class 'dict_items'>


In [ ]:
# key를 통해 value 얻기
num_dict.get(2) 
print(num_dict.get(2))
print('\n')

# 해당 key가 딕셔너리 안에 있는지 조사
print(1 in num_dict) # 있으면 True
print(4 in num_dict)# 없으면 False
print('\n')

# 딕셔너리의 key, value 모두 제거
num_dict.clear()
print(num_dict)

two


True
False


{}


# 1-6. 집합

**집합 생성 및 요소 접근하기**

집합은 요소로 이루어진 자료형이라는 점에서 리스트나 튜플과 비슷하지만

요소들간의 중복이 허용되지 않으며, 요소들의 순서도 없다.


In [ ]:
# 집합명 = set(요소들)

numSet1 = set([1, 2, 3])
strSet = set('Hello')
print(numSet1)
print(strSet)

# 변수 타입 확인하기
print(type(numSet1))
print('\n')

# 집합 연산
numSet2 = set([3, 4, 5])

print('numSet1과 numSet2의 교집합 : ', numSet1 & numSet2) # 교집합
print('numSet1과 numSet2의 합집합 : ', numSet1 | numSet2) # 합집합
print('numSet1과 numSet2의 차집합 : ', numSet1 - numSet2) # 차집합

# difference를 사용한 차집합
print('numSet1과 numSet2의 차집합(difference) : ', numSet1.difference(numSet2)) 


{1, 2, 3}
{'e', 'o', 'H', 'l'}
<class 'set'>


numSet1과 numSet2의 교집합 :  {3}
numSet1과 numSet2의 합집합 :  {1, 2, 3, 4, 5}
numSet1과 numSet2의 차집합 :  {1, 2}
numSet1과 numSet2의 차집합(difference) :  {1, 2}


**집합 관련 함수**

값 1개 추가 : add

값 여러 개 추가 : update

특정 값 제거 : remove

In [ ]:
# 값 1개 추가
numSet1.add(4)
print(numSet1)

# 값 여러 개 추가
numSet1.update([5, 6, 7])
print(numSet1)

# 특정 값 제거
numSet1.remove(5)
print(numSet1)


{1, 2, 3, 4}
{1, 2, 3, 4, 5, 6, 7}
{1, 2, 3, 4, 6, 7}


# 2. 제어문 살펴보기

**조건문의 비교 연산자**

In [ ]:
a = 1
b = 2

True_or_False = a > b
print('a > b ? ', True_or_False)

True_or_False = a < b
print('a < b ? ', True_or_False)

True_or_False = a >= b
print('a >= b ? ', True_or_False)

True_or_False = a <= b
print('a <= b ? ', True_or_False)

True_or_False = a == b
print('a == b ? ', True_or_False)

True_or_False = a != b
print('a != b ? ', True_or_False)


a > b ?  False
a < b ?  True
a >= b ?  False
a <= b ?  True
a == b ?  False
a != b ?  True


**2-1. if문**

조건문을 테스트해서 참이면 if문 바로 다음 블록을 수행



In [ ]:
# 기본 if문 사용하기
if 3>2:
    print("3>2 is True")

# if, else 사용하기
numList=[3, 6, 9, 10, 13, 15]
picknum = numList[0]
if picknum < numList[1]:
    print("picknum is smaller than 6")
else:
    print("picknum is larger than 6")
    
# if, elif, else 사용하기
print("pick ten in numList")
picknum = numList[3]
if picknum < numList[2]:
    print("%d is smaller than %d. pick another number." % (picknum,numList[2]))
elif picknum > numList[4]:
    print("%d is larger than %d. pick another number." % (picknum,numList[4]))
elif picknum == 9 or picknum == 13:
    print("pick another number.")
else:
    print("You picked the right number")

3>2 is True
picknum is smaller than 6
pick ten in numList
You picked the right number


**2-2. while문**

while문은 조건문이 참인 동안 while문 아래 블록을 반복 수행



In [ ]:
index = 3

# index가 1보다 클 때까지만 수행하는 while문
while index > 1: 
    print("index is %d" % index)
    index = index - 1
print('\n')

idx = 0
while idx < 10:
    idx = idx + 1
    if idx == 5: # idx가 5이면 아래 블록을 건너뛰고 while의 조건문으로 이동
        continue
    if idx == 7: # idx가 7이면 while문 빠져나오기
        break
    if idx % 2 == 0:
        print("{} is even number.".format(idx))
    else:
        print("{} is odd number.".format(idx))

index is 3
index is 2


1 is odd number.
2 is even number.
3 is odd number.
4 is even number.
6 is even number.


**2-3. for문**

for문은 시퀀스를 이용하여 반복 수행하는 제어문이다.



In [ ]:
# 기본 for문 수행하기
for i in [1, 3, 5]:
    print(i)
print('\n')

# 두 개 이상의 변수를 활용한 for문
for (food, drink) in [('hamburger', 'coca-cola'), ('sandwitch', 'milk')]:
    print("I like to eat {} with {}".format(food, drink))
print('\n')

# range로 시작 범위와 끝 범위를 직접 지정한 for문
for i in range(2, 5):
    print(i)
print('\n')

# range와 len 함수(길이 구하기 함수)를 사용한 for문
charlist = ['a', 'b', 'c']
for i in range(len(charlist)):
    print(charlist[i])

1
3
5


I like to eat hamburger with coca-cola
I like to eat sandwitch with milk


2
3
4


a
b
c


In [ ]:
# len 함수는 머신러닝에서 많이 사용되므로 꼭 숙지할 것
numList = [1,2,3]
numTuple = (1,2,3)
strvar = 'School'
print(len(numList))
print(len(numTuple))
print(len(strvar))

3
3
6


# 3. 파이썬 라이브러리

In [ ]:
import numpy as np
import pandas as pd
import sklearn
import scipy
import mglearn

ModuleNotFoundError: ignored

# 4. 머신러닝에서의 벡터, 행렬 연산

머신러닝에서 이루어지는 대부분의 연산은 스칼라(scalar), 벡터(vector), 행렬(matrix) 및 배열(array 혹은 tensor)을 기반으로 이루어진다.

파이썬에서 배열을 연산할 때는 상황에 맞는 연산자들을 알고 적절히 사용해야 의도한 연산이 가능하다.

가장 중요한 개념은 변수의 차원(dimension)으로, 차원이란 데이터가 구성된 형태를 나타낸다.

**데이터의 차원수(dimension)**

In [ ]:
import numpy as np

a = np.array(3)
print('a는 %d axis 데이터'%(a.ndim))

b = np.array([3, 6, 9])
print('b는 %d axis 데이터'%(b.ndim))

c = np.array([[3, 6, 9], [2, 4, 8]])
print('c는 %d axes 데이터'%(c.ndim))

a는 0 axis 데이터
b는 1 axis 데이터
c는 2 axes 데이터


위 코드에서 변수 a는 '하나의 숫자로 이루어진 변수'로, 이러한 데이터를 '스칼라'라 한다.

b는 두 개 이상의 숫자로 이루어진 변수로, '벡터'라 하며,

c는 두 개의 벡터로 이루어진 '행렬'이라 한다.

ndim은 데이터를 구성하는 축(axis)의 개수를 반환하는데, '변수를 감싸는 대괄호([ ])의 개수를 반환한다'라고 생각하면 쉬우며,

머신러닝 프레임워크인 tensorflow에서 사용되는 배열 자료형인 tensor의 rank와 같은 개념으로 볼 수 있다.

tensorflow에서 tensor는 일반적으로 3차원 이상의 배열을 부른다.

즉, 변수 c는 2 axes 데이터로, 데이터의 개수는 2개이며, 각 데이터는 3개의 수로 이루어진 벡터라 말할 수 있다.

자칫 머리가 복잡해질 수 있으나, 우리는 머신러닝에서 데이터를 어떻게 표현하는가를 알기만 하면 된다.

머신러닝에서는 어떤 데이터를 표현할 때 보통 '데이터의 개수 x 데이터의 차원수'로 표현한다. 

예를 들어, 60000개의 숫자 이미지로 구성된 MNIST 데이터의 경우 각 이미지는 28x28의 크기를 가지는데, 

이러한 경우 우리는 '60000x28x28'을 '데이터의 차원수'라 부른다. 

같은 방식으로 변수 c를 표현하면 간단하게 '2x3 차원 데이터'라 표현할 수 있다.

따라서 머신러닝에서는 데이터의 형태를 파악할 때 shape를 가장 많이 사용하게 된다.

In [ ]:
print('a는 {} 차원 데이터'.format(a.shape))
print('b는 {} 차원 데이터'.format(b.shape))
print('c는 {} 차원 데이터'.format(c.shape))

a는 () 차원 데이터
b는 (3,) 차원 데이터
c는 (2, 3) 차원 데이터


**매트리스 연산**

먼저, 간단한 행렬 연산을 생각해본다.

아래는 파이썬에서의 곱연산자를 사용하여 행렬을 곱한 결과이다.

In [3]:
a = np.array([1, 2])
a_s = 3 * a
print(a_s)
a_dot = np.dot(3, a)
print(a_dot)

[3 6]
[3 6]


In [4]:
a_mul = np.matmul(3, a)

ValueError: ignored

위처럼 행렬 a의 원소들에 스칼라 값을 곱한 결과를 얻을 수 있다.

다음은 행렬곱 연산을 수행해본다.

In [5]:
a = np.array([[1, 2]])
b = np.array([[3, 4]])
c = a * b
print(c)

[[3 8]]


별연산자를 사용한 위 결과는 같은 인덱스의 원소끼리 곱하는 element-wise 곱연산이 수행된 것이다.

하지만 일반적인 행렬곱 연산을 수행하고 싶다면 다른 연산자를 사용해야 한다.

a 와 b 두 행렬은 1x2 행렬이며, 이 두 행렬을 곱하기 위해서는 두 행렬 중 하나를 전치해야 한다.

b를 전치하여 2x1로 만들어 행렬곱을 수행하면 1x1의 연산값을 얻을 수 있을 것이다.

In [6]:
b_t = b.T # b를 transpose
print(a.shape)
print(b_t.shape)

c = np.matmul(a, b_t)
print(c)
d = np.dot(a, b_t)
print(d)

(1, 2)
(2, 1)
[[11]]
[[11]]


**데이터 합치기**

머신러닝에서는 상황에 따라 행렬을 붙여 연결시켜야 할 때도 있다.

특히, 나누어진 데이터를 하나의 변수에 집어넣어야 할 경우 아래와 같이 np.concatenate를 사용하여 데이터를 이어붙일 수 있다.

아래 코드를 통해 100x6차원의 두 클래스에 대한 데이터를 하나의 변수로 통합하는 과정을 살펴본다.

In [7]:
# 데이터 생성
x_c1 = np.random.randint(100, size = (100, 6))
x_c2 = np.random.randint(100, size = (100, 6))
# 클래스 할당
y_c1 = np.zeros((100))
y_c2 = np.ones((100))
print("before concatenation")
print("x_c1, c2 dimension : {}, {}".format(x_c1.shape, x_c2.shape))
print("y_c1, c2 dimension : {}, {}".format(y_c1.shape, y_c2.shape))
print('\n')

x_data = np.concatenate((x_c1, x_c2))
y_class = np.concatenate((y_c1, y_c2))

print("after concatenation")
print("x_data dimension : {}".format(x_data.shape))
print("y_class dimension : {}".format(y_class.shape))

before concatenation
x_c1, c2 dimension : (100, 6), (100, 6)
y_c1, c2 dimension : (100,), (100,)


after concatenation
x_data dimension : (200, 6)
y_class dimension : (200,)


**최소값 최대값 찾기 및 데이터 정규화**

머신러닝에서는 데이터의 값이 클 경우에는 학습이 잘 진행되지 않는 경우가 있다. 

이러한 경우 데이터의 정규화를 통해 작은 범위의 값을 가지도록 변경하는 정규화 과정을 거치게 된다.

이 때, 최소값과 최대값을 활용하여 데이터의 모든 값이 0~1 사이의 값을 가지도록 할 수 있다.

In [8]:
min_x = x_data.min()
max_x = x_data.max()
print("before min-max scaling")
print("x_data 의 min 값 : {}".format(min_x))
print("x_data 의 max 값 : {}".format(max_x))
print('\n')

# min-max scaling
x_scale = (x_data - min_x) / (max_x - min_x)
print(x_scale, '\n')
print("after min-max scaling")
print("x_scale 의 min 값 : {}".format(x_scale.min()))
print("x_scale 의 max 값 : {}".format(x_scale.max()))

before min-max scaling
x_data 의 min 값 : 0
x_data 의 max 값 : 99


[[0.76767677 0.05050505 0.8989899  0.4040404  0.62626263 0.66666667]
 [0.57575758 0.24242424 0.14141414 0.26262626 0.3030303  0.27272727]
 [0.12121212 0.57575758 0.25252525 0.22222222 0.34343434 0.33333333]
 ...
 [0.02020202 0.96969697 0.23232323 0.97979798 0.09090909 0.29292929]
 [0.73737374 0.26262626 0.         0.11111111 0.92929293 0.45454545]
 [0.27272727 0.96969697 0.2020202  0.98989899 0.42424242 0.92929293]] 

after min-max scaling
x_scale 의 min 값 : 0.0
x_scale 의 max 값 : 1.0
